### ISSUE TITLE
Failure to determine intersections after rotation

### ISSUE THREAD

**Issue by ngffy** [jan-mue/geometer#24]
```python
from geometer import *

foo = Cuboid(Point(0,0,-10), Point(1,0,-10), Point(0,1,-10), Point(0,0,10))
bar = Cuboid(Point(-10,-10,0), Point(10,-10,0), Point(-10,10,0), Point(-10,-10,1))

transform = rotation(3.14/6, -Point(1,0,0))

print(foo.intersect(bar))
print(foo.intersect(transform*bar))
```

This code shows that the intersections are found before `bar` is rotated, but not after.

**Comment by jan-mue** [comment]
Intersections of polyhedra with other polyhedra are not yet supported by the package (see [documentation](https://geometer.readthedocs.io/en/stable/source/geometer.html#geometer.shapes.Polyhedron.intersect)). Currently the intersect method of a polyhedron will try to calculate the intersection of its faces with the object that was given as argument. The intersect method of the faces (of the Polygon class) then delegates again to the intersect method of its edges. The intersect method of the edges then reverses the two objects i.e. tries to intersect the second cuboid with all edges of the first one. I think there should be a type check in the Polygon and Polyhedron classes to reject arguments of type Polyhedron.

Other than the issue with the unsupported intersection operation, there is a real bug in the code that calculates the intersection of a polygon with a line. The following code is enough to reproduce the issue:
```python
from geometer import Point, Line, Rectangle, rotation

l = Line(Point(0, 0, -10), Point(0, 0, 10))
r = Rectangle(Point(-10, -10, 0), Point(10, -10, 0), Point(10, 10, 0), Point(-10, 10, 0))
transform = rotation(3.14/6, Point(1, 0, 0))

assert (transform*r).intersect(l) == [Point(0, 0, 0)]
```

The issue is probably caused by numerical instability that causes the method `Polygon.contains()` to return false for the point of intersection of the polygon's plane and the line.
