### ISSUE TITLE
ValueError thrown during intersection between rectangle and segment

### ISSUE THREAD

**Issue by ngffy** [jan-mue/geometer#25]
```python
from geometer import *

foo = Rectangle(Point(148.06094049635456, 10.151151779987144, 60.522099063951394), Point(129.78569335065157, -42.129870038015355, 60.54878245579997), Point(85.91668756014471, -26.79517716452499, 60.41723371984577), Point(104.19193470584759, 25.485844653477507, 60.390550327997126))
bar = Segment(Point(-38.9592826559563, -6.703132040294841, 64.78693707404751), Point(133.01711836447913, -6.633886165038485, 54.310634812542006))

print(foo.intersect(bar))
```

Sorry about the ugly numbers with this one. This rectangle and segment shouldn't intersect, but when run it throws a ValueError.

> Traceback (most recent call last):
...
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by jan-mue** [comment]
The issue is caused by very small values in the array that describes the plane of the rectangle. It results in a direction vector that is close to zero in all components and such a vector is up to a numerical error a multiple of any vector i.e. equal to any point in homogeneous coordinates. Hence the ray used in the Polygon.contains method seems to have only a single vertex which is what caused the ValueError.
